#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Copyright (C) 2022 MediaTek Inc.
# Author: Ramax Lo <ramax.lo@mediatek.com>
# Licensed on MIT

simplerootfs_enabled() {
	return 0
}

find_rootdev()
{
	local dev=`/sbin/blkid | grep "$1" | awk -F ':' '{print $1}'`

	if [ -z "$dev" ]; then
		echo "/nodev"
	fi

	echo $dev
}

simplerootfs_run() {
        if [ -z "$ROOTFS_DIR" ]; then
		return
        fi

	if ! mountpoint -q $ROOTFS_DIR; then
		if [ -n "$bootparam_root" ]; then
			info "Mounting $bootparam_root"

			if [ "`echo ${bootparam_root} | cut -c1-5`" = "UUID=" ]; then
				root_uuid=`echo $bootparam_root | cut -c6-`
				bootparam_root=`find_rootdev "$root_uuid"`
			elif [ "`echo ${bootparam_root} | cut -c1-9`" = "PARTUUID=" ]; then
				root_partuuid=`echo $bootparam_root | cut -c10-`
				bootparam_root=`find_rootdev "$root_partuuid"`
			elif [ "`echo ${bootparam_root} | cut -c1-10`" = "PARTLABEL=" ]; then
				root_partlabel=`echo $bootparam_root | cut -c11-`
				bootparam_root=`find_rootdev "$root_partlabel"`
			elif [ "`echo ${bootparam_root} | cut -c1-6`" = "LABEL=" ]; then
				root_label=`echo $bootparam_root | cut -c7-`
				bootparam_root=`find_rootdev "$root_label"`
			fi

			if [ -e "$bootparam_root" ]; then
				flags=""
				if [ -n "$bootparam_ro" ] && ! echo "$bootparam_rootflags" | grep -w -q "ro"; then
					if [  -n "$bootparam_rootflags" ]; then
						bootparam_rootflags="$bootparam_rootflags,"
					fi
					bootparam_rootflags="${bootparam_rootflags}ro"
				fi
				if [ -n "$bootparam_rootflags" ]; then
					flags="$flags -o$bootparam_rootflags"
				fi
				if [ -n "$bootparam_rootfstype" ]; then
					flags="$flags -t$bootparam_rootfstype"
				fi
				mount $flags $bootparam_root $ROOTFS_DIR
				if ! mountpoint -q $ROOTFS_DIR; then
					msg "simplerootfs: Something wrong here"
				fi
			fi
		fi
	fi
}
